packages:
  - '.'
  - 'packages/*'
verifyDepsBeforeRun: false
allowBuilds:
  esbuild: true
  sharp: true
  '@tailwindcss/oxide': true
  '@central-icons-react/round-outlined-radius-2-stroke-1.5': true
overrides:
  vite: 8.2.2
