// Story-only access to the licensed Central Icons markup generated by
// scripts/generate-story-icons.mjs. Not part of the component package.
import { nothing } from 'lit';
import data from './generated/icons.json';

export type IconEntry = [name: string, words: string, svg: string];
export const iconEntries = data as IconEntry[];
export const hasIconLibrary = iconEntries.length > 0;

const byName = new Map(iconEntries.map(e => [e[0], e[2]]));

// Plain plus, drawn to the Figma icon spec (outlined, radius 2, stroke 1.5). It stands in
// for any picked icon when the licensed library is not installed.
const FALLBACK = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg>';

/** An `<svg>` element for a picked icon name, ready to place in a component slot. */
export function iconNode(name: string | undefined, slot?: string): Element | typeof nothing {
  if (!name) return nothing;
  const template = document.createElement('template');
  template.innerHTML = byName.get(name) ?? FALLBACK;
  const svg = template.content.firstElementChild!;
  svg.setAttribute('aria-hidden', 'true');
  if (slot) svg.setAttribute('slot', slot);
  return svg;
}
